project_id = "rbkuplzntpayendbfzud"

[functions.send-transfer-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.create-mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false
